name: particleini
version: 0.1.5
description: "A simple INI parser for C++"

git-repo: "https://github.com/handicraftsman/particleini"
git-tag: v0.1.5

targets:
  particleini:
    type: library
    sources:
      - "particleini.cpp"
    include-dirs:
      - "."
    cpp: "c++11"
